### ISSUE TITLE
Rely on global pinning

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/rvlib-feedstock#21]
This feedstock pins an extreme amount of packages, to the extend of reproducing large (but severely outdated!) parts of the global pinning. It can be necessary to pin 1-2 dependencies if upstream is not yet compatible with the newest versions in conda-forge, but this is not the way it should be done.

**Comment by knaaptime** [comment]
Hey, thanks for raising. I'm happy to help however i can, but not sure I'm following. The [recipe](https://github.com/conda-forge/rvlib-feedstock/blob/dd9600aa7fc79c0b344e3e60a717d7a62c608ac7/recipe/meta.yaml#L37) itself is pretty sparse... where are the pins coming into play?

**Comment by knaaptime** [comment]
ah, maybe [here](https://github.com/conda-forge/rvlib-feedstock/blob/main/recipe/conda_build_config.yaml)?

I didn't enter any of those manually, so if there's a way to trim it down, thats great

**Comment by h-vetinari** [comment]
> ah, maybe [here](https://github.com/conda-forge/rvlib-feedstock/blob/main/recipe/conda_build_config.yaml)?

Yes exactly. Your local copy takes precedence, and since it's outdated, that's not good. Your `conda_build_config.yaml` should be empty (or minimal). Could you try deleting it and then rerendering the feedstock?

**Comment by knaaptime** [comment]
sure i'll give it a shot. The only awkward thing is the recipe *needs* to use the mingw toolchain on windows, so that's the only thing i'll need to set somewhere. I thought that was handled [here](https://github.com/conda-forge/rvlib-feedstock/blob/dd9600aa7fc79c0b344e3e60a717d7a62c608ac7/recipe/meta.yaml#L24), but i ran into issues getting things figured out as the conda build system has evolved. That's probably the original source of the massive file

thanks for the help

**Comment by h-vetinari** [comment]
> The only awkward thing is the recipe _needs_ to use the mingw toolchain on windows

That can be handled independently of the pinning (or leave only that in the `conda_build_config.yaml`). 🙃
